columns:
  id: int64
  Gender: object
  Age: int64
  Driving_License: int64
  Region_Code: float64
  Previously_Insured: int64
  Vehicle_Age: object
  Vehicle_Damage: object
  Annual_Premium: float64
  Policy_Sales_Channel: float64
  Vintage: int64
  Response: int64

numerical_columns:
  - Age
  - Annual_Premium
  - Vintage

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

drop_columns:
  - id

target_column: Response
